Repository eduardosantoshf/t-tracker, pull requests merged in 2021-06, with the labels that each got.

#16 Merge Tests to UI into Develop
  .github/workflows/deliveries-engine.yml
  deliveries-engine/deliveries-engine/.classpath
  deliveries-engine/deliveries-engine/pom.xml
  deliveries-engine/deliveries-engine/src/test/java/deliveries_engine/webpage/HomePage.java
  deliveries-engine/deliveries-engine/src/test/java/deliveries_engine/webpage/LoginPage.java
  deliveries-engine/deliveries-engine/src/test/java/deliveries_engine/webpage/NavigationSteps.java
  deliveries-engine/deliveries-engine/src/test/java/deliveries_engine/webpage/NavigationTests.java
  deliveries-engine/deliveries-engine/src/test/resources/deliveries_engine/webpage/navigation.feature
  deliveries-engine/web/index.html
  deliveries-engine/web/login.html
Labels: frontend, test

#25 New features to deployment branch
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/controller/StoreController.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/model/Delivery.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/repository/RiderRepository.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/security/SecurityConfig.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/service/RiderServiceImp.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/service/StoreService.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/service/StoreServiceImp.java
  deliveries-engine/deliveries-engine/src/test/java/deliveries_engine/repository/DeliveryRepositoryTest.java
  deliveries-engine/docker-compose.yml
  deliveries-engine/web/Dockerfile
  deliveries-engine/web/assets/js/auth.js
  deliveries-engine/web/dashboard.html
  deliveries-engine/web/index.html
  deliveries-engine/web/login.html
  deliveries-engine/web/position.html
  deliveries-engine/web/signup.html
Labels: deployment

#26 Feature/register store
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/controller/RiderController.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/controller/StoreController.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/exception/ErrorWarning.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/model/Store.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/repository/StoreRepository.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/security/SecurityConfig.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/service/RiderService.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/service/RiderServiceImp.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/service/StoreService.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/service/StoreServiceImp.java
  deliveries-engine/deliveries-engine/src/test/java/deliveries_engine/controller/RiderControllerTest.java
  deliveries-engine/deliveries-engine/src/test/java/deliveries_engine/controller/StoreControllerTest.java
  deliveries-engine/deliveries-engine/src/test/java/deliveries_engine/repository/StoreRepositoryTest.java
Labels: feature

#28 Update do status do rider
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/controller/RiderController.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/service/RiderService.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/service/RiderServiceImp.java
Labels: feature

#24 Merge user registration into develop
  t-tracker/t-tracker/pom.xml
  t-tracker/t-tracker/src/main/java/t_tracker/CorsConfiguration.java
  t-tracker/t-tracker/src/main/java/t_tracker/PasswordEncoderConfig.java
  t-tracker/t-tracker/src/main/java/t_tracker/controller/ClientController.java
  t-tracker/t-tracker/src/main/java/t_tracker/model/Client.java
  t-tracker/t-tracker/src/main/java/t_tracker/model/Coordinates.java
  t-tracker/t-tracker/src/main/java/t_tracker/model/Lab.java
  t-tracker/t-tracker/src/main/java/t_tracker/model/Order.java
  t-tracker/t-tracker/src/main/java/t_tracker/model/Owner.java
  t-tracker/t-tracker/src/main/java/t_tracker/model/Product.java
  t-tracker/t-tracker/src/main/java/t_tracker/model/Rider.java
  t-tracker/t-tracker/src/main/java/t_tracker/model/Stock.java
  t-tracker/t-tracker/src/main/java/t_tracker/model/Store.java
  t-tracker/t-tracker/src/main/java/t_tracker/model/User.java
  t-tracker/t-tracker/src/main/java/t_tracker/model/VaccineBuy.java
  t-tracker/t-tracker/src/main/java/t_tracker/model/VaccineCollection.java
  t-tracker/t-tracker/src/main/java/t_tracker/repository/ClientRepository.java
  t-tracker/t-tracker/src/main/java/t_tracker/repository/LabRepository.java
  t-tracker/t-tracker/src/main/java/t_tracker/repository/OrderRepository.java
  t-tracker/t-tracker/src/main/java/t_tracker/repository/UserRepository.java
  t-tracker/t-tracker/src/main/java/t_tracker/security/JWTAuthorizationFilter.java
  t-tracker/t-tracker/src/main/java/t_tracker/security/JwtAuthenticationFilter.java
  t-tracker/t-tracker/src/main/java/t_tracker/security/SecurityConfig.java
  t-tracker/t-tracker/src/main/java/t_tracker/service/ClientService.java
  t-tracker/t-tracker/src/main/java/t_tracker/service/ClientServiceImpl.java
  t-tracker/t-tracker/src/main/java/t_tracker/service/JwtTokenService.java
  t-tracker/t-tracker/src/main/java/t_tracker/service/UserDetailsServiceImpl.java
  t-tracker/t-tracker/src/main/resources/application.properties
  t-tracker/t-tracker/src/test/java/t_tracker/JsonUtil.java
  t-tracker/t-tracker/src/test/java/t_tracker/controller/ClientControllerTest.java
  t-tracker/t-tracker/src/test/java/t_tracker/repository/ClientRepositoryTests.java
  t-tracker/t-tracker/src/test/java/t_tracker/repository/LabRepositoryTests.java
  t-tracker/t-tracker/src/test/java/t_tracker/repository/OrderRepositoryTests.java
  t-tracker/t-tracker/src/test/java/t_tracker/service/ClientServiceUnitTests.java
  t-tracker/t-tracker/src/test/resources/application.properties
Labels: backend, feature, test

#31 Add rating and comment + get ratings and comments of a rider
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/controller/StoreController.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/model/Rider.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/security/SecurityConfig.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/service/StoreService.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/service/StoreServiceImp.java
Labels: feature

#35 tests on ratings and comments
  deliveries-engine/deliveries-engine/src/test/java/deliveries_engine/controller/StoreControllerTest.java
Labels: test

#37 Feature/websockets
  deliveries-engine/deliveries-engine/pom.xml
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/security/SecurityConfig.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/service/StoreServiceImp.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/websocket/Warning.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/websocket/WarningController.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/websocket/WebSocketConfig.java
  deliveries-engine/web/assets/js/sockjs-0.3.4.js
  deliveries-engine/web/assets/js/stomp.js
  deliveries-engine/web/index.html
Labels: backend, feature, frontend

#38 rider and store service tests
  deliveries-engine/deliveries-engine/.idea/workspace.xml
  deliveries-engine/deliveries-engine/deliveries-engine.iml
  deliveries-engine/deliveries-engine/src/test/java/deliveries_engine/service/RiderServiceTest.java
  deliveries-engine/deliveries-engine/src/test/java/deliveries_engine/service/StoreServiceTest.java
  deliveries-engine/deliveries-engine/target/classes/application.properties
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/CorsConfiguration.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/DeliveriesEngineApplication.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/PasswordEncoderConfig.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/controller/Controller.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/controller/RiderController.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/controller/StoreController.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/exception/ErrorWarning.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/model/Admin.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/model/Delivery.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/model/Rider.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/model/Store.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/model/User.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/repository/AdminRepository.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/repository/DeliveryRepository.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/repository/RiderRepository.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/repository/StoreRepository.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/repository/UserRepository.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/security/JWTAuthorizationFilter.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/security/JwtAuthenticationFilter.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/security/SecurityConfig.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/service/JwtTokenService.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/service/RiderService.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/service/RiderServiceImp.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/service/Service.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/service/ServiceImp.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/service/StoreService.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/service/StoreServiceImp.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/service/UserDetailsServiceImpl.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/swagger2/Swagger2Config.class
  deliveries-engine/deliveries-engine/target/test-classes/deliveries_engine/repository/DeliveryRepositoryTest.class
  deliveries-engine/deliveries-engine/target/test-classes/deliveries_engine/repository/StoreRepositoryTest.class
Labels: backend, test

#44 Develop features to deployment
  .github/workflows/deliveries-engine.yml
  .github/workflows/t-tracker.yml
  README.md
  deliveries-engine/deliveries-engine/.idea/workspace.xml
  deliveries-engine/deliveries-engine/deliveries-engine.iml
  deliveries-engine/deliveries-engine/pom.xml
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/security/SecurityConfig.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/service/StoreServiceImp.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/websocket/Warning.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/websocket/WarningController.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/websocket/WebSocketConfig.java
  deliveries-engine/deliveries-engine/src/test/java/deliveries_engine/controller/StoreControllerTest.java
  deliveries-engine/deliveries-engine/src/test/java/deliveries_engine/service/RiderServiceTest.java
  deliveries-engine/deliveries-engine/src/test/java/deliveries_engine/service/StoreServiceTest.java
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/DeliveriesEngineApplication.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/PasswordEncoderConfig.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/controller/Controller.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/model/Admin.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/model/User.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/repository/AdminRepository.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/repository/DeliveryRepository.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/repository/UserRepository.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/security/JWTAuthorizationFilter.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/security/JwtAuthenticationFilter.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/service/JwtTokenService.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/service/Service.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/service/ServiceImp.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/service/UserDetailsServiceImpl.class
  deliveries-engine/deliveries-engine/target/classes/deliveries_engine/swagger2/Swagger2Config.class
  deliveries-engine/deliveries-engine/target/test-classes/deliveries_engine/repository/DeliveryRepositoryTest.class
  deliveries-engine/deliveries-engine/target/test-classes/deliveries_engine/repository/StoreRepositoryTest.class
  deliveries-engine/web/assets/css/leaflet.css
  deliveries-engine/web/assets/js/dashboard.js
  deliveries-engine/web/assets/js/leaflet.js
  deliveries-engine/web/assets/js/position.js
  deliveries-engine/web/assets/js/sockjs-0.3.4.js
  deliveries-engine/web/assets/js/stomp.js
  deliveries-engine/web/dashboard.html
  deliveries-engine/web/index.html
  deliveries-engine/web/position.html
  reporting/TQS_Product_Specification_Report.docx
  reporting/TQS_QA_Manual.pdf
Labels: deployment

#53 CI/CD monitoring API finished
  .DS_Store
  monitoring/main.py
  monitoring/requirements.txt
Labels: deployment, feature

#54 fixed websockets by adding store location
  deliveries-engine/deliveries-engine/.idea/workspace.xml
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/model/Store.java
  deliveries-engine/deliveries-engine/src/main/java/deliveries_engine/service/StoreServiceImp.java
Labels: bug, feature, frontend

#58 global stats on frontend
  .DS_Store
  deliveries-engine/.DS_Store
  deliveries-engine/web/assets/js/globalStats.js
  deliveries-engine/web/globalStats.html
Labels: feature, frontend

#61 Merge Lab Stock Management into Develop
  t-tracker/t-tracker/src/main/java/t_tracker/DataLoader.java
  t-tracker/t-tracker/src/main/java/t_tracker/controller/ClientController.java
  t-tracker/t-tracker/src/main/java/t_tracker/controller/LabController.java
  t-tracker/t-tracker/src/main/java/t_tracker/controller/OrderController.java
  t-tracker/t-tracker/src/main/java/t_tracker/controller/ProductController.java
  t-tracker/t-tracker/src/main/java/t_tracker/model/Coordinates.java
  t-tracker/t-tracker/src/main/java/t_tracker/model/Lab.java
  t-tracker/t-tracker/src/main/java/t_tracker/model/Order.java
  t-tracker/t-tracker/src/main/java/t_tracker/model/Product.java
  t-tracker/t-tracker/src/main/java/t_tracker/model/Stock.java
  t-tracker/t-tracker/src/main/java/t_tracker/model/User.java
  t-tracker/t-tracker/src/main/java/t_tracker/security/JwtAuthenticationFilter.java
  t-tracker/t-tracker/src/main/java/t_tracker/service/ClientServiceImpl.java
  t-tracker/t-tracker/src/main/java/t_tracker/service/JwtTokenService.java
  t-tracker/t-tracker/src/main/java/t_tracker/service/LabService.java
  t-tracker/t-tracker/src/main/java/t_tracker/service/LabServiceImpl.java
  t-tracker/t-tracker/src/main/java/t_tracker/service/OrderServiceImpl.java
  t-tracker/t-tracker/src/test/java/t_tracker/controller/ClientControllerIntegrationTests.java
  t-tracker/t-tracker/src/test/java/t_tracker/controller/LabControllerIntegrationTests.java
  t-tracker/t-tracker/src/test/java/t_tracker/controller/LabControllerTest.java
  t-tracker/t-tracker/src/test/java/t_tracker/controller/OrderControllerTest.java
  t-tracker/t-tracker/src/test/java/t_tracker/controller/ProductControllerIntegrationTests.java
  t-tracker/t-tracker/src/test/java/t_tracker/controller/ProductControllerTest.java
  t-tracker/t-tracker/src/test/java/t_tracker/repository/ProductRepositoryTests.java
  t-tracker/t-tracker/src/test/java/t_tracker/repository/StockRepositoryTests.java
  t-tracker/t-tracker/src/test/java/t_tracker/service/LabServiceUnitTests.java
  t-tracker/t-tracker/src/test/java/t_tracker/service/OrderServiceUnitTests.java
  t-tracker/t-tracker/src/test/java/t_tracker/service/ProductServiceTests.java
Labels: backend, feature, test
